### ISSUE TITLE
Server connection issues

### ISSUE THREAD

**Issue by s1l3nt78** [Technowlogy-Pushpender/nekros#1]
So I'm not sure if you have done this on purpose or..... but yeah i thought I'd bring it up. Once trying to run the main.py file it continuously came back with "cannot connect to server error" which I eventually managed to debug to it looking for 'nekros.nekros_keys' which they out an error as the .sql file creates a ranspy_keys table which is solved by changing the database nekros looks for in stage1.py or recreating the ranspy_keys table as nekros_keys. 

The second issue is once running the file and having the test files encrypted, I use the machine id on the get_decode page which spits out a key about twice the length. Looking at db_manager's key output for that target the key was right until the last 8 characters or so which needed to be manually copied from db_manager after pasting the correct ones from the sight. Other then the manual copy I haven't found a fix as python is not my first language /:

Anyway thanks! Love the repos otherwise!
*s1l3nt78

**Comment by Technowlogy-Pushpender** [comment]
I updated the ```nekros.sql``` ,  if you are facing any issue while decryption, then try to manually extract decryption key from nekros table 

And then use ```reverse_attack.py``` to reverse the attack,

All files are coded in such a way that, each file can run on its own like this: python3 reverse_attack.py

Run stage1.py like this: python stage1.py

Stage1 is responsible for database connection and it creates the machine id as well as the decryption key which is then used by the other stages

You can even run each stage one by one in Series, 

I mentioned in the ```Readme.md```
That which stage corresponds to which task

**Comment by s1l3nt78** [comment]
I saw that they run independantly which is why I managed to get it all working, Just wanted to inform you of the errors, after copying just over half of what the php page gives and manually checking and inputting the last few characters the decryption works. But this will no-doubt cause bigger issues for anyone using the program large-scale and remotely. (Not that anyone should, as spreading ransomware is against the law.....  : | ) but yeah im happy to fork with the fix but as python isnt my strongest programming language I just wanted to let you know what the problems were in order to make patching it easier
