### ISSUE TITLE
error starting main.py

### ISSUE THREAD

**Issue by Mrcosta20** [Technowlogy-Pushpender/nekros#2]
good night friend first of all thank you very much for that interesting and good project both this and the keylogger, good the following errors when I start the python main.py. And even though I already update the information in the config.txt file with the server data, these errors appear to me and I don't know what else to modify or if those config.txt files have to change the extensions or if you can create a script where you can verify connections to the server before starting main.py thanks

[*] Initiating Stage 1 ...
[!] Unable to Connect to Server!

**Comment by Technowlogy-Pushpender** [comment]
Run stage1.py, each stage file can be run individually, stage1 is
responsible for creating machine id and decryption/encryption key

Which are used by the other stages

Everything is mentioned in the documentation that which stage is
responsible to perform which task

Make sure that you are able to connect to the website, and the database
name and the table name is correct

**Comment by Mrcosta20** [comment]
hola amigo pues mira lo que me sale cuando ejecuto el python stage1.py
*] Initiating Stage 1 ...
Traceback (most recent call last):
  File "C: \ Python37-32 \ lib \ site-packages \ mysql \ connector \ network.py", line 606, in open_connection
    self.sock.connect (sockaddr)
ConnectionRefusedError: [WinError 10061] A connection cannot be established as the destination computer expressly denied that connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stage1.py", line 66, in <module>
    unique_machine_id, key = test.start ()
  File "stage1.py", line 29, in start
    key = self.gen_encrypt_key_and_export (unique_machine_id) #Generating & Exporting KEY
  File "stage1.py", line 41, in gen_encrypt_key_and_export
    mydb = mysql.connector.connect (host = self.server, user = self.username, passwd = self.password, database = self.db_name)
  File "C: \ Python37-32 \ lib \ site-packages \ mysql \ connector \ __ init__.py", line 219, in connect
    return MySQLConnection (* args, ** kwargs)
  File "C: \ Python37-32 \ lib \ site-packages \ mysql \ connector \ connection.py", line 104, in __init__
    self.connect (** kwargs)
  File "C: \ Python37-32 \ lib \ site-packages \ mysql \ connector \ abstracts.py", line 960, in connect
    self._open_connection ()
  File "C: \ Python37-32 \ lib \ site-packages \ mysql \ connector \ connection.py", line 288, in _open_connection
    self._socket.open_connection ()
  File "C: \ Python37-32 \ lib \ site-packages \ mysql \ connector \ network.py", line 609, in open_connection
    errno = 2003, values ​​= (self.get_address (), _strioerror (err)))
mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'localhost: 3306' (10061 Unable to establish a connection since the destination computer expressly denied that connection)

Could you tell me what happened or if when I run stage1.py where my phpMyAdmin is hosted, it denies me the connection, thanks for your help

**Comment by Technowlogy-Pushpender** [comment]
Maybe you are using nekros over WAN and you have not changed the server_url
which is by default localhost

**Comment by Mrcosta20** [comment]
I do not use WAN I use localhost but it is a free hosting that does not give access to root user that will be the problem, but in your config.txt file in the Ransom folder it says (server = localhost) if it is like that or in that part that would go my url where the files are hosted or where is the nekros.sql ??

and another thing is server_url or server = localhost

**Comment by Technowlogy-Pushpender** [comment]
If you want to use this program over the internet then setup free hosting

Set the server url to the website url
And setup the database to that free hosting site

Database file nekros.sql and website files are available in the project

Or you can test it locally, just install campo
And setup database,

Leave everything as it i.e. server url is equal to localhost and that it
run the main.py

**Comment by Mrcosta20** [comment]
good night friend because I already tried in a thousand ways to enable Remote MySQL but nothing enables my ip addresses in my cpanel but I also don't know why the program does not start, I already tried python main.py and python stage1.py but neither of them don't know if you could make a video on youtube explaining the procedure of this great ransomware because in truth I show you nothing what I get in the console when starting the stage1.py in the different alternatives I add in the server
![error de opcion 1](https://user-images.githubusercontent.com/62074731/78418531-9c267680-7602-11ea-841c-01d9d03ae93b.jpg)
![error de opcion 2](https://user-images.githubusercontent.com/62074731/78418532-a0eb2a80-7602-11ea-9c82-46463228d638.jpg)

**Comment by Mrcosta20** [comment]
the key, the username and name of the database I already added them well I do not know why it does not connect when I start the main.py or stage1.py, and of course I want to start the program offline since by xampp if It works well

**Comment by Mrcosta20** [comment]
all the files in the web folder and uploaded them to my hosting as you can see
![pantalla](https://user-images.githubusercontent.com/62074731/78418630-8796ae00-7603-11ea-948b-a0e5d38fb955.jpg)

**Comment by Technowlogy-Pushpender** [comment]
The only problem you are facing it that you have not filled the credentials
correctly in the config.txt or you have leave it blank

Make sure that you are filling the credentials correctly

Under the [DB_CRED]
Fill the database creds, if the server is offline, then the ransomeware
will just quit, this is because in first stage it creates the key which is
absolutely random md5 hash

Stage1.py script will upload the decryption key to the server to make that
you didn't lose the key

And also this key is not saved in the victim system,

This is the config.txt file which is used by stage1.py

https://github.com/Technowlogy-Pushpender/nekros/blob/master/Ransomeware/config.txt

**Comment by Mrcosta20** [comment]
good afternoon friend to tell you that the program can finally run thank you very much I have other questions but better close this thread and open another one, thank you very much for your help
