### ISSUE TITLE
Unable to Connect to Server!

### ISSUE THREAD

**Issue by ittech25** [Technowlogy-Pushpender/nekros#4]
Windows 10 
python 3.7 ==> OK
install requirement ==> ok
pip install image ==> ok
mysql ==> Connect ok
IIS localhost run php ==> test Machine ID // Request My Decryption OK

Upload Website Folder's Content to your server and update get_decrypt_code.php with right creds. present in website/php/ ==> DONE
Create Database and Import nekros.sql in it. ==> DONE
Update config.txt present in Ransomeware folder. ==> DONE
Update config.txt present in db_manager folder to Manage database using GUI Window. ==> DONE
$ python -m pip install requirements.txt ==> DONE
Run main.py like this ==> ERROR

[*] Initiating Stage 1 ...
[!] Unable to Connect to Server!

![image](https://user-images.githubusercontent.com/63135414/79068621-84ca4600-7cf2-11ea-9772-c38f4ddd8d80.png)

TEST Website ==> Query mySQL OK
![image](https://user-images.githubusercontent.com/63135414/79068626-901d7180-7cf2-11ea-8f9f-88d5bc216a46.png)

![image](https://user-images.githubusercontent.com/63135414/79068635-9dd2f700-7cf2-11ea-99bb-5d0a3fbc1198.png)

**Comment by Technowlogy-Pushpender** [comment]
Make sure you place all database creds in the config.txt otherwise, it will
not be able to connect to the database

config.txt is placed inside Ransomeware folder

**Comment by ittech25** [comment]
Sure update config.txt in Ransomeware folder
and inside db_manager folder and Website/php/get_decrypt_code.php.

Try change localhost to 127.0.0.1 but same error

**Comment by Technowlogy-Pushpender** [comment]
Please send the image of config.txt
Maybe you are surrounding the creds with quotation

**Comment by ittech25** [comment]
![image](https://user-images.githubusercontent.com/63135414/79069595-9c58fd00-7cf9-11ea-935f-2628ba6a255e.png)

Thank you for quick response

**Comment by Technowlogy-Pushpender** [comment]
Run stage1.py like this python stage1.py

Each stage and after_stage file can be executed individually

Stage1 file is responsible for database connection and decryption key and
machine id creation

Just run it and find out the actual error

**Comment by ittech25** [comment]
Thanks Bro. I will update result tomorrow.

**Comment by ittech25** [comment]
hi @Technowlogy-Pushpender 
i run stage 1 with error output

![image](https://user-images.githubusercontent.com/63135414/79084746-9c8be380-7d5f-11ea-92f5-2b7e7d23b211.png)

**Comment by ittech25** [comment]
Finally, error with mysql 
Fixed it :

SET @@GLOBAL.sql_mode= 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

![image](https://user-images.githubusercontent.com/63135414/79085317-4b312380-7d62-11ea-9eee-bffc84f6e84a.png)

Thank you @Technowlogy-Pushpender support.
